### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [abwahed/GoogleSearchScraper#3]
Hello Abdul 👋 , thank you for your effort on the code submission. I am Olivier at Nimble, and I will be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
@abwahed I have now completed the first round of code reviews. I have focused on the key issues that would need your attention to ensure we can complete this process in the coming days.

I look forward to your feedback on all open issues.

**Comment by abwahed** [comment]
Hi Olivier, nice to here from you. I will try to be as responsive as possible and fix the issues ASAP, so that this code review process is completed within 2-3 days.

**Comment by olivierobert** [comment]
@abwahed I noticed that you have opened 3 new PRs (#9, #10 and #11). So I have checked those already. While you have merged them, I have added a few comments to some of them. It would be good to have your feedback on the comment and issues as well.

**Comment by abwahed** [comment]
@olivierobert I have worked on the issues and feedbacks given by you. I want to let you know that I am working on this review process alongside my todos at my current company. I hope you understand my situation for the delay here. Looking forward to your feedbacks.

**Comment by olivierobert** [comment]
@abwahed I have now reviewed all the latest changes and added some comments via the open PRs. We now have sufficient information to wrap up the code challenge review and can close this recruitment stage. Thank you for your efforts 🙏 Our team will provide our feedback to you by email in the coming days.
